import { test, expect } from '@playwright/test'
import { validateContent } from '../scripts/validate-content.ts'

const catalog = validateContent().lessons
const latest = catalog[0]
const question = latest.reading.question
const wrongAnswer = (question.answer + 1) % 4
const correctLetter = String.fromCharCode(65 + (latest.day - 1) % 4)
const partialProgress = JSON.stringify({ vocab: { [latest.vocabulary[0].id]: 'mastered' }, readingAnswers: null })
const canonicalDate = '2026-09-08'
const canonicalDateIndex = catalog.findIndex((lesson) => lesson.date === canonicalDate)

async function reading(page: import('@playwright/test').Page) {
  await page.getByRole('button', { name: '読解練習', exact: true }).click()
}
test('fresh activity starts at zero and completion, theme and review status persist', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page).toHaveTitle('N1 Immersive Sparring Partner')
  await expect(page.locator('.hero h1')).toBeVisible()
  await expect(page.locator('vite-error-overlay')).toHaveCount(0)
  await expect(page.locator('.mini-streak')).toContainText('0日')
  await page.getByRole('button', { name: '没入読解', exact: true }).click()
  await page.getByRole('button', { name: '日中対訳', exact: true }).click()
  await expect(page.locator('.zh-translation')).toHaveCount(latest.immersion.paragraphs.length)
  await page.getByRole('button', { name: '解説', exact: true }).click()
  await expect(page.locator('.analysis-note')).toHaveCount(latest.immersion.paragraphs.length)
  await page.getByRole('button', { name: '読了にする', exact: true }).click()
  await expect(page.locator('.mini-streak')).toContainText('1日')
  await page.getByRole('button', { name: 'N1 語彙', exact: true }).click()
  await page.getByRole('button', { name: '要復習', exact: true }).first().click()
  await page.getByRole('button', { name: '読解テーマを切り替える', exact: true }).click()
  await page.reload()
  await expect(page.locator('.app')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('.mini-streak')).toContainText('1日')
  await page.getByRole('button', { name: '没入読解', exact: true }).click()
  await expect(page.getByRole('button', { name: '読了済み', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '誤答復習', exact: true }).click()
  await expect(page.locator('.review-row').filter({ hasText: latest.vocabulary[0].word })).toBeVisible()
  expect(errors).toEqual([])
})
test('wrong answer can be retried from review without losing the earlier attempt', async ({ page }, testInfo) => {
  await page.goto('/'); await reading(page)
  await page.locator('.answer-option').filter({ hasText: question.options[wrongAnswer] }).click()
  await page.getByRole('button', { name: '回答する', exact: true }).click()
  await expect(page.locator('.result-title')).toHaveText(`正解：${correctLetter}`)
  await page.getByRole('button', { name: '誤答復習', exact: true }).click()
  const wrong = page.locator('.review-row').filter({ hasText: '本文に戻り、主張を支える根拠' })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await wrong.getByRole('button', { name: /復習する/ }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'もう一度挑戦する', exact: true }).click()
  await expect(page.locator('.answer-option:disabled')).toHaveCount(0)
  await expect(page.locator('.result-panel')).toHaveCount(0)
  expect(await page.evaluate(id => JSON.parse(localStorage.getItem('n1-progress')!).readingAnswers[id], question.id)).toBe(wrongAnswer)
  await page.getByRole('button', { name: '前回の結果に戻る' }).click()
  await expect(page.locator('.result-title')).toHaveText(`正解：${correctLetter}`)
  await page.getByRole('button', { name: 'もう一度挑戦する', exact: true }).click()
  await page.locator('.answer-option').filter({ hasText: question.options[question.answer] }).click()
  await page.getByRole('button', { name: '回答する', exact: true }).click()
  await expect(page.locator('.result-title')).toHaveText('正解です')
  await page.reload(); await reading(page)
  await page.getByText('回答履歴（2回）', { exact: true }).click()
  await expect(page.locator('.attempt-history li')).toHaveCount(2)
  await expect(page.locator('.attempt-history li').first()).toContainText('不正解')
  await page.locator('.result-panel').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('reading-retry-history.png') })
  await page.getByRole('button', { name: '誤答復習', exact: true }).click()
  await expect(page.locator('.review-row').filter({ hasText: '本文に戻り、主張を支える根拠' })).toHaveCount(0)
  await page.locator('.date-dropdown-trigger').click()
  await page.locator('.date-dropdown-option').last().click(); await reading(page)
  await expect(page.getByRole('button', { name: '回答する', exact: true })).toBeDisabled()
  await expect(page.locator('.answer-option:disabled')).toHaveCount(0)
})
test('old canonical answers remain correct after display reordering', async ({ page }) => {
  expect(canonicalDateIndex).toBeGreaterThanOrEqual(0)
  await page.addInitScript(() => localStorage.setItem('n1-progress', JSON.stringify({
    vocab: { 'v-haaku': 'mastered' }, grammar: {}, readingAnswers: { '2026-09-08-q-main': 2 }, streak: 11,
  })))
  await page.goto('/')
  await expect(page.locator('.mini-streak')).toContainText('0日')
  await page.locator('.date-dropdown-trigger').click()
  await page.locator('.date-dropdown-option').nth(canonicalDateIndex).click(); await reading(page)
  await expect(page.locator('.result-title')).toHaveText('正解です')
  await expect(page.locator('.answer-option.correct .answer-letter')).toHaveText('B')
  await expect(page.locator('.answer-option.selected .answer-letter')).toHaveText('B')
  await page.getByText('回答履歴（1回）', { exact: true }).click()
  await expect(page.locator('.attempt-history')).toContainText('以前の記録（日付不明） · B · 正解')
})
for (const damaged of ['{}', 'null', '{broken', partialProgress]) {
  test(`damaged progress recovers visibly: ${damaged}`, async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
    await page.addInitScript(value => localStorage.setItem('n1-progress', value), damaged)
    await page.goto('/')
    await expect(page.locator('.hero h1')).toBeVisible()
    await expect(page.getByRole('status')).toContainText('読み込めなかった')
    await page.getByRole('button', { name: 'N1 語彙', exact: true }).click()
    if (damaged === partialProgress) await expect(page.locator('.status-btn.mastered')).toHaveCount(1)
    expect(errors).toEqual([])
  })
}
test('blocked writes keep the app usable and retry persists in-memory work', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.addInitScript(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function(key, value) {
      if (!sessionStorage.getItem('allow-write')) throw new DOMException('Quota exceeded', 'QuotaExceededError')
      return original.call(this, key, value)
    }
    Object.defineProperty(window, 'allowWrites', { value: () => original.call(sessionStorage, 'allow-write', 'yes') })
  })
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('保存できません')
  await page.getByRole('button', { name: '没入読解', exact: true }).click()
  await page.getByRole('button', { name: '読了にする', exact: true }).click()
  await page.evaluate(() => (window as unknown as {allowWrites: () => void}).allowWrites())
  await page.getByRole('button', { name: '保存を再試行' }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.reload()
  await page.getByRole('button', { name: '没入読解', exact: true }).click()
  await expect(page.getByRole('button', { name: '読了済み', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
test('choosing C for every lesson is no longer a perfect score', async ({ page }) => {
  await page.goto('/')
  let correct = 0
  for (let index = 0; index < catalog.length; index++) {
    await page.locator('.date-dropdown-trigger').click()
    await page.locator('.date-dropdown-option').nth(index).click(); await reading(page)
    await page.locator('.answer-option').nth(2).click()
    await page.getByRole('button', { name: '回答する', exact: true }).click()
    if (await page.locator('.result-title').innerText() === '正解です') correct++
  }
  expect(correct).toBe(catalog.filter(lesson => (lesson.day - 1) % 4 === 2).length)
  expect(correct).toBeLessThan(catalog.length)
})
test('search and mobile Japanese reading remain usable in dark mode', async ({ page }, testInfo) => {
  const logs: string[] = []; page.on('console', message => { if (['error', 'warning'].includes(message.type())) logs.push(message.text()) })
  await page.goto('/')
  await page.getByRole('textbox', { name: '毎日のN1教材を検索' }).fill('かんかつ')
  await expect(page.locator('.daily-search-result')).toHaveCount(2)
  await page.locator('.daily-search-result').first().click()
  await expect(page.locator('.section-header h2')).toHaveText('N1 語彙')
  await page.getByRole('button', { name: '没入読解', exact: true }).click()
  await page.getByRole('button', { name: '読解テーマを切り替える', exact: true }).click()
  await expect(page.locator('.jp-body').first()).toHaveCSS('color', 'rgb(241, 244, 241)')
  await page.screenshot({ path: testInfo.outputPath('desktop-dark.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: '日中対訳', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('mobile-dark.png') })
  await page.getByRole('button', { name: 'ナビゲーションを開く' }).click()
  await page.getByRole('button', { name: '学習履歴', exact: true }).click()
  await expect(page.locator('.history-row-button')).toHaveCount(catalog.length)
  expect(logs).toEqual([])
})
