import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

const unit = '2026-09-30-okashi-bokuso'
const storageKey = 'n1-live-reactions-progress-v1'
const screenshots = '/tmp/n1-improvements-playwright/okashi-bokuso'

test('new unit is reachable from the sidebar and contains complete source-labelled study cards', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (['error', 'warning'].includes(message.type())) errors.push(message.text()) })
  await page.goto('/')
  await expect(page).toHaveTitle('N1 Immersive Sparring Partner')
  await page.getByRole('navigation', { name: 'メインナビゲーション', exact: true }).getByRole('button', { name: '直播条反', exact: true }).click()
  await expect(page.getByLabel('选择学习单元', { exact: true })).toHaveValue(unit)
  await expect(page.locator('#live-unit-title')).toHaveText('ドラえもん「おかし牧草」')
  await expect(page.locator('[data-live-group]')).toHaveCount(28)
  await expect(page.locator('.live-entry')).toHaveCount(47)
  await expect(page.locator('.live-source-quote')).toHaveCount(28)
  await expect(page.locator('[data-live-group]').first().locator('.live-source-quote')).toContainText('手机笔记')
  await expect(page.locator('vite-error-overlay')).toHaveCount(0)
  await mkdir(screenshots, { recursive: true })
  await page.screenshot({ path: `${screenshots}/desktop.png` })
  const categories = page.getByRole('group', { name: '内容分类', exact: true })
  await categories.getByRole('button', { name: /漫画双关/ }).click()
  await expect(page.locator('[data-live-group]')).toHaveCount(2)
  await page.getByLabel('选择知识组', { exact: true }).selectOption('live-2026-09-30-kau')
  await expect(page.locator('[data-live-group]')).toHaveCount(1)
  await expect(page.locator('.live-source-quote')).toContainText('この草でチョコをかうんだ。')
  await page.locator('[data-live-group]').scrollIntoViewIfNeeded()
  await page.screenshot({ path: `${screenshots}/wordplay.png` })
  await categories.getByRole('button', { name: /自动词／他动词/ }).click()
  await expect(page.locator('[data-live-group]')).toHaveCount(2)
  await expect(page.getByLabel('选择知识组', { exact: true })).toHaveValue('all')
  await page.getByRole('button', { name: '重置筛选', exact: true }).click()
  await page.getByLabel('搜索本页笔记', { exact: true }).fill('つかいはたす')
  await expect(page.locator('[data-live-group]')).toHaveCount(1)
  await page.getByLabel('搜索本页笔记', { exact: true }).fill('不存在的知识点')
  await expect(page.getByRole('heading', { name: '没有匹配的知识组' })).toBeVisible()
  await page.getByRole('button', { name: '清除筛选', exact: true }).click()
  await expect(page.locator('[data-live-group]')).toHaveCount(28)
  expect(errors).toEqual([])
})

test('legacy marks, new marks and daily progress survive unit changes and reloads independently', async ({ page }) => {
  await page.addInitScript(key => {
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify({ version: 1, groups: { 'live-2026-09-28-endurance': 'mastered' } }))
  }, storageKey)
  await page.goto('/')
  const nav = page.getByRole('navigation', { name: 'メインナビゲーション', exact: true })
  await nav.getByRole('button', { name: 'N1 語彙', exact: true }).click()
  await page.locator('.learning-card').first().getByRole('button', { name: '習得済み', exact: true }).click()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('n1-progress'))).toContain('mastered')
  const dailyBefore = await page.evaluate(() => [localStorage.getItem('n1-progress'), localStorage.getItem('n1-completed-lessons')])
  await nav.getByRole('button', { name: '直播条反', exact: true }).click()
  await page.locator('[data-live-group]').first().getByRole('button', { name: '要復習', exact: true }).click()
  await page.getByRole('group', { name: '内容分类', exact: true }).getByRole('button', { name: /漫画双关/ }).click()
  await page.getByLabel('搜索本页笔记', { exact: true }).fill('买')
  await page.getByLabel('选择学习单元', { exact: true }).selectOption('2026-09-28')
  await expect(page.getByLabel('搜索本页笔记', { exact: true })).toHaveValue('')
  await expect(page.locator('[data-live-group]')).toHaveCount(15)
  await expect(page.locator('.live-entry')).toHaveCount(64)
  await expect(page.locator('[data-live-group]').first().getByRole('button', { name: '習得済み', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await expect(page.getByLabel('选择学习单元', { exact: true })).toHaveValue('2026-09-28')
  await page.getByLabel('选择学习单元', { exact: true }).selectOption(unit)
  await expect(page.locator('[data-live-group]').first().getByRole('button', { name: '要復習', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('group', { name: '筛选学习状态', exact: true }).getByRole('button', { name: '要復習', exact: true }).click()
  await expect(page.locator('[data-live-group]')).toHaveCount(1)
  await page.reload()
  await expect(page.getByLabel('选择学习单元', { exact: true })).toHaveValue(unit)
  expect(await page.evaluate(() => [localStorage.getItem('n1-progress'), localStorage.getItem('n1-completed-lessons')])).toEqual(dailyBefore)
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), storageKey)
  expect(saved.groups['live-2026-09-28-endurance']).toBe('mastered')
  expect(saved.groups['live-2026-09-30-exhaust']).toBe('review')
})

test('mobile unit picker, categories and dark cards remain readable at narrow widths', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#live-reactions')
  await expect(page.locator('[data-live-group]')).toHaveCount(28)
  await mkdir(screenshots, { recursive: true })
  await page.screenshot({ path: `${screenshots}/mobile.png` })
  await page.getByRole('button', { name: 'ナビゲーションを開く', exact: true }).click()
  await page.getByRole('button', { name: '表示テーマを切り替える', exact: true }).click()
  const backdrop = page.getByRole('button', { name: 'ナビゲーションを閉じる', exact: true })
  const bounds = await backdrop.boundingBox()
  if (!bounds) throw new Error('No visible drawer backdrop')
  await backdrop.click({ position: { x: bounds.width - 12, y: 12 } })
  await expect(page.locator('.app')).toHaveAttribute('data-theme', 'dark')
  await page.getByLabel('选择知识组', { exact: true }).selectOption('live-2026-09-30-sae')
  await page.locator('[data-live-group]').scrollIntoViewIfNeeded()
  await page.screenshot({ path: `${screenshots}/mobile-dark.png` })
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  }
})

test('invalid unit URLs fall back without losing the live section', async ({ page }) => {
  await page.goto('/?live-unit=invalid#live-reactions')
  await expect(page.getByLabel('选择学习单元', { exact: true })).toHaveValue(unit)
  await expect(page.locator('[data-live-group]')).toHaveCount(28)
  await expect(page).toHaveURL(/live-unit=2026-09-30-okashi-bokuso#live-reactions$/)
})
